import { useState, useEffect, useCallback } from 'react';
import { Pencil, Plus, Mail, Lock, User as UserIcon, Phone, Link2, Unlink } from 'lucide-react';
import { userService } from '@/services/user.service';
import UserLifecycleActions from '@/components/users/UserLifecycleActions';
import Table, { type Column } from '@/components/ui/Table';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Modal from '@/components/ui/Modal';
import Input from '@/components/ui/Input';
import SearchBar from '@/components/ui/SearchBar';
import { formatPhone } from '@/utils/formatters';
import type { User } from '@/types';
import toast from 'react-hot-toast';
const emptyForm={firstName:'',lastName:'',email:'',phone:'',password:''};type FormData=typeof emptyForm;
export default function ParentsPage(){
 const [parents,setParents]=useState<User[]>([]);const [pagination,setPagination]=useState({page:1,totalPages:1,total:0});const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState<string|null>(null);const [childrenError,setChildrenError]=useState<string|null>(null);const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState<'all'|'active'|'inactive'>('all');const [modalOpen,setModalOpen]=useState(false);const [childrenModal,setChildrenModal]=useState<User|null>(null);const [children,setChildren]=useState<User[]>([]);const [allStudents,setAllStudents]=useState<User[]>([]);const [selectedStudentIds,setSelectedStudentIds]=useState<string[]>([]);const [childrenLoading,setChildrenLoading]=useState(false);const [associationLoading,setAssociationLoading]=useState(false);const [editingUser,setEditingUser]=useState<User|null>(null);const [form,setForm]=useState<FormData>({...emptyForm});const [formErrors,setFormErrors]=useState<Partial<Record<keyof FormData,string>>>({});const [saving,setSaving]=useState(false);
 const fetchParents=useCallback(async()=>{setLoading(true);setLoadError(null);try{const params:Record<string,string|number>={page:pagination.page,limit:20,role:'PARENT'};if(search)params.search=search;if(statusFilter!=='all')params.isActive=statusFilter==='active';const res=await userService.getUsers(params as any);setParents(res.data);setPagination({page:res.pagination.page,totalPages:res.pagination.totalPages,total:res.pagination.total})}catch(error){const message=error instanceof Error?error.message:'Impossible de charger les parents';setLoadError(message);toast.error(message)}finally{setLoading(false)}},[pagination.page,search,statusFilter]);useEffect(()=>{fetchParents()},[fetchParents]);
 const openCreate=()=>{setEditingUser(null);setForm({...emptyForm});setFormErrors({});setModalOpen(true)};const openEdit=(u:User)=>{setEditingUser(u);setForm({firstName:u.firstName||'',lastName:u.lastName||'',email:u.email||'',phone:u.phone||'',password:''});setFormErrors({});setModalOpen(true)};
 const showChildren=async(parent:User)=>{setChildrenModal(parent);setChildrenLoading(true);setChildrenError(null);setSelectedStudentIds([]);try{const [linked,studentPage]=await Promise.all([userService.getStudentsByParent(parent.id),userService.getUsers({role:'STUDENT',page:1,limit:100})]);setChildren(linked);setAllStudents(studentPage.data);setSelectedStudentIds(linked.map(s=>s.id))}catch(error){const message=error instanceof Error?error.message:'Impossible de charger les élèves';setChildrenError(message);toast.error(message)}finally{setChildrenLoading(false)}};
 const toggleStudent=(id:string)=>setSelectedStudentIds(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);const saveAssociations=async()=>{if(!childrenModal)return;setAssociationLoading(true);try{const currentIds=new Set(children.map(c=>c.id));const selectedIds=new Set(selectedStudentIds);const toAdd=[...selectedIds].filter(id=>!currentIds.has(id));const toRemove=[...currentIds].filter(id=>!selectedIds.has(id));await Promise.all([...toAdd.map(id=>userService.linkParentStudent(childrenModal.id,id)),...toRemove.map(id=>userService.unlinkParentStudent(childrenModal.id,id))]);const refreshed=await userService.getStudentsByParent(childrenModal.id);setChildren(refreshed);setSelectedStudentIds(refreshed.map(s=>s.id));toast.success('Associations mises à jour')}catch(error){toast.error(error instanceof Error?error.message:'Impossible de mettre à jour les associations')}finally{setAssociationLoading(false)}};
 const unlinkChild=async(student:User)=>{if(!childrenModal)return;setAssociationLoading(true);try{await userService.unlinkParentStudent(childrenModal.id,student.id);const refreshed=await userService.getStudentsByParent(childrenModal.id);setChildren(refreshed);setSelectedStudentIds(refreshed.map(s=>s.id));toast.success('Élève retiré du parent')}catch(error){toast.error(error instanceof Error?error.message:'Impossible de retirer l’association')}finally{setAssociationLoading(false)}};
 const validate=()=>{const errors:typeof formErrors={};if(!form.firstName.trim())errors.firstName='Requis';if(!form.lastName.trim())errors.lastName='Requis';if(!editingUser&&!form.password)errors.password='Requis';setFormErrors(errors);return Object.keys(errors).length===0};const handleSave=async()=>{if(!validate())return;setSaving(true);try{if(editingUser)await userService.updateUser(editingUser.id,{firstName:form.firstName,lastName:form.lastName,email:form.email,phone:form.phone} as any);else await userService.createUser({...form,role:'PARENT'} as any);toast.success(editingUser?'Parent modifié':'Parent ajouté');setModalOpen(false);await fetchParents()}catch(error){toast.error(error instanceof Error?error.message:'Impossible d’enregistrer le parent')}finally{setSaving(false)}};
 const columns:Column<User>[]=[{key:'name',header:'Nom complet',render:u=><span className="font-medium text-slate-900">{u.firstName} {u.lastName}</span>},{key:'matricule',header:'Matricule',render:u=><span className="text-sm text-slate-600">{u.matricule||'—'}</span>},{key:'email',header:'E-mail',render:u=><span className="text-sm text-slate-600">{u.email||'—'}</span>},{key:'phone',header:'Téléphone',render:u=><span className="text-sm text-slate-600">{formatPhone(u.phone)}</span>},{key:'children',header:'Enfants',render:u=><button aria-label={`Gérer les enfants de ${u.firstName} ${u.lastName}`} onClick={()=>showChildren(u)} className="inline-flex items-center gap-1 rounded-md bg-primary-50 px-2 py-1 text-xs font-medium text-primary"><Link2 className="h-3 w-3"/>Gérer</button>},{key:'isActive',header:'Statut',render:u=>u.isActive?<span className="inline-flex rounded-md bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700">Actif</span>:<span className="inline-flex rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700">Inactif</span>},{key:'actions',header:'Actions',className:'text-right',render:u=><div className="flex items-center justify-end gap-1"><button aria-label={`Modifier ${u.firstName} ${u.lastName}`} onClick={()=>openEdit(u)} className="rounded-md p-1.5 text-slate-400 hover:bg-primary-50 hover:text-primary"><Pencil className="h-4 w-4"/></button><UserLifecycleActions user={u} onChanged={fetchParents} label={`le parent ${u.firstName} ${u.lastName}`}/></div>}];
 return <div className="space-y-5"><div className="flex flex-col gap-3 border-b border-line pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-semibold tracking-tight text-slate-900">Parents</h1><p className="mt-1 text-sm text-muted">Gérez les responsables et associez un ou plusieurs élèves à chaque parent.</p></div><Button onClick={openCreate}><Plus className="h-4 w-4"/>Ajouter un parent</Button></div><div className="flex flex-col gap-2 sm:flex-row sm:items-center"><div className="w-full sm:max-w-sm"><SearchBar onSearch={v=>{setSearch(v);setPagination(p=>({...p,page:1}))}} placeholder="Rechercher un parent..."/></div><div className="flex gap-1 rounded-md border border-line bg-white p-1"><button className={`rounded px-3 py-1.5 text-xs font-medium ${statusFilter==='all'?'bg-slate-100 text-slate-900':'text-slate-500'}`} onClick={()=>{setStatusFilter('all');setPagination(p=>({...p,page:1}))}}>Tous</button><button className={`rounded px-3 py-1.5 text-xs font-medium ${statusFilter==='active'?'bg-emerald-50 text-emerald-700':'text-slate-500'}`} onClick={()=>{setStatusFilter('active');setPagination(p=>({...p,page:1}))}}>Actifs</button><button className={`rounded px-3 py-1.5 text-xs font-medium ${statusFilter==='inactive'?'bg-red-50 text-red-700':'text-slate-500'}`} onClick={()=>{setStatusFilter('inactive');setPagination(p=>({...p,page:1}))}}>Inactifs</button></div></div>{loadError&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{loadError}</div>}<Card className="!p-0 overflow-hidden"><Table columns={columns} data={parents} loading={loading} keyExtractor={u=>u.id} emptyMessage="Aucun parent trouvé"/></Card>
 <Modal open={modalOpen} onClose={()=>setModalOpen(false)} title={editingUser?'Modifier le parent':'Ajouter un parent'} size="lg"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Input label="Prénom" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} error={formErrors.firstName} icon={<UserIcon className="h-4 w-4"/>}/><Input label="Nom" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} error={formErrors.lastName}/><Input label="E-mail" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} icon={<Mail className="h-4 w-4"/>}/><Input label="Téléphone" type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} icon={<Phone className="h-4 w-4"/>}/>{!editingUser&&<Input label="Mot de passe" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} error={formErrors.password} icon={<Lock className="h-4 w-4"/>}/>}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={()=>setModalOpen(false)}>Annuler</Button><Button onClick={handleSave} loading={saving}>{editingUser?'Enregistrer':'Créer'}</Button></div></Modal>
 <Modal open={!!childrenModal} onClose={()=>{setChildrenModal(null);setChildrenError(null)}} title={`Élèves associés à ${childrenModal?.firstName} ${childrenModal?.lastName}`} size="lg">{childrenLoading?<div className="py-8 text-center text-slate-400">Chargement...</div>:childrenError?<div className="py-6 text-center text-sm text-red-600">{childrenError}</div>:<div className="space-y-5"><div><p className="mb-2 text-sm font-semibold text-slate-900">Élèves du parent</p>{children.length===0?<p className="rounded-md border border-dashed border-line p-4 text-sm text-slate-400">Aucun élève associé.</p>:<div className="divide-y divide-line rounded-md border border-line">{children.map(c=><div key={c.id} className="flex items-center justify-between p-3"><div><p className="text-sm font-medium text-slate-900">{c.firstName} {c.lastName}</p><p className="text-xs text-muted">{c.className||'Classe inconnue'} · {c.matricule||'—'}</p></div><button type="button" onClick={()=>unlinkChild(c)} disabled={associationLoading} className="rounded-md p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600"><Unlink className="h-4 w-4"/></button></div>)}</div>}</div><div><p className="mb-2 text-sm font-semibold text-slate-900">Ajouter plusieurs élèves</p><div className="max-h-64 space-y-1 overflow-y-auto rounded-md border border-line p-2">{allStudents.map(student=><label key={student.id} className="flex cursor-pointer items-center gap-3 rounded-md px-3 py-2 hover:bg-slate-50"><input type="checkbox" checked={selectedStudentIds.includes(student.id)} onChange={()=>toggleStudent(student.id)} disabled={associationLoading}/><span><span className="block text-sm font-medium text-slate-800">{student.firstName} {student.lastName}</span><span className="block text-xs text-muted">{student.className||'Classe inconnue'} · {student.matricule||'—'}</span></span></label>)}</div></div><div className="flex justify-end gap-3"><Button variant="secondary" onClick={()=>setChildrenModal(null)}>Fermer</Button><Button onClick={saveAssociations} loading={associationLoading}><Link2 className="h-4 w-4"/>Enregistrer</Button></div></div>}</Modal></div>;
}
