import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { ChevronRight, GraduationCap, Settings, ShieldCheck } from 'lucide-react-native';
import { useNavigation } from '@react-navigation/native';
import { Colors, Spacing, FontSize, BorderRadius } from '@/theme';
import authService from '@/services/auth.service';
import type { Child, User } from '@/types';
import type { RootStackParamList } from '@/navigation/types';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';

type Nav = NativeStackNavigationProp<RootStackParamList>;
export default function ProfileScreen() {
  const navigation = useNavigation<Nav>();
  const [user, setUser] = useState<User | null>(null);
  const [children, setChildren] = useState<Child[]>([]);
  useEffect(() => { void (async () => { const stored = await authService.getStoredUser(); setUser(stored); if (stored?.role === 'parent') { const profile = await authService.getProfile().catch(() => null); setChildren(profile?.children ?? []); } })(); }, []);
  const role = user?.role === 'parent' ? 'Parent' : user?.role === 'student' ? 'Élève' : 'Personnel';
  const initials = user?.full_name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() ?? 'EC';
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.header}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><Text style={styles.name}>{user?.full_name ?? 'Utilisateur'}</Text><Text style={styles.role}>{role}</Text></View><View style={styles.card}><View style={styles.row}><ShieldCheck size={18} color={Colors.primary} /><View><Text style={styles.caption}>Matricule</Text><Text style={styles.value}>{user?.matricule ?? '—'}</Text></View></View><View style={styles.row}><GraduationCap size={20} color={Colors.primary} /><View><Text style={styles.caption}>Établissement</Text><Text style={styles.value}>{user?.establishment_name ?? 'Votre établissement'}</Text></View></View></View>{user?.role === 'parent' && children.length > 0 ? <View><Text style={styles.sectionTitle}>Mes enfants</Text>{children.map((child) => <View key={child.id} style={styles.child}><View style={styles.childAvatar}><Text style={styles.childInitials}>{child.full_name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</Text></View><View style={styles.childText}><Text style={styles.childName}>{child.full_name}</Text><Text style={styles.childDetails}>{child.class_name || 'Classe non renseignée'} · {child.matricule}</Text></View></View>)}</View> : null}<TouchableOpacity style={styles.settings} onPress={() => navigation.navigate('Auth', { screen: 'Login' })}><Settings size={20} color={Colors.gray600} /><Text style={styles.settingsText}>Paramètres</Text><ChevronRight size={20} color={Colors.gray300} /></TouchableOpacity><TouchableOpacity style={styles.logout} onPress={() => void authService.logout()}><Text style={styles.logoutText}>Se déconnecter</Text></TouchableOpacity></ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.xl, paddingBottom: Spacing['3xl'] }, header: { alignItems: 'center', marginBottom: Spacing.xl }, avatar: { width: 84, height: 84, borderRadius: 42, backgroundColor: Colors.primary, alignItems: 'center', justifyContent: 'center', marginBottom: Spacing.md }, avatarText: { color: Colors.white, fontSize: FontSize.xl, fontWeight: '800' }, name: { color: Colors.gray900, fontSize: FontSize.xl, fontWeight: '800' }, role: { color: Colors.gray500, fontSize: FontSize.sm, marginTop: 3 }, card: { backgroundColor: Colors.white, borderRadius: BorderRadius.xl, padding: Spacing.lg, marginBottom: Spacing.xl }, row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingVertical: Spacing.md }, caption: { color: Colors.gray500, fontSize: FontSize.xs }, value: { color: Colors.gray900, fontSize: FontSize.md, fontWeight: '700', marginTop: 2 }, sectionTitle: { color: Colors.gray900, fontSize: FontSize.lg, fontWeight: '800', marginBottom: Spacing.md }, child: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: BorderRadius.lg, padding: Spacing.md, marginBottom: Spacing.sm }, childAvatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#E8F5E9', alignItems: 'center', justifyContent: 'center' }, childInitials: { color: Colors.primary, fontWeight: '800' }, childText: { flex: 1, marginLeft: Spacing.md }, childName: { color: Colors.gray900, fontWeight: '700' }, childDetails: { color: Colors.gray500, fontSize: FontSize.xs, marginTop: 3 }, settings: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: BorderRadius.lg, padding: Spacing.lg, marginTop: Spacing.lg }, settingsText: { flex: 1, marginLeft: Spacing.md, color: Colors.gray700, fontWeight: '600' }, logout: { marginTop: Spacing.md, alignItems: 'center', padding: Spacing.md }, logoutText: { color: Colors.danger, fontWeight: '700' } });
