import { FormEvent, useState } from 'react';
import { ArrowRight, KeyRound, LockKeyhole, Phone, ShieldCheck } from 'lucide-react';
import { authApi, ApiError } from '../services/api';
import type { User } from '../types';

interface LoginProps { onAuthenticated: (token: string, user: User) => void; }
type LoginRole = 'PARENT' | 'STUDENT' | 'STAFF';
export default function Login({ onAuthenticated }: LoginProps) {
  const [role, setRole] = useState<LoginRole>('PARENT'); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function handleSubmit(event: FormEvent) { event.preventDefault(); setError(''); setBusy(true); try { const result = await authApi.login(role, identifier.trim(), password); onAuthenticated(result.token, result.user); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Impossible de se connecter.'); } finally { setBusy(false); } }
  return <main className="min-h-[100dvh] bg-paper px-5 py-8 text-ink sm:px-10 lg:px-16"><div className="mx-auto grid min-h-[calc(100dvh-4rem)] max-w-6xl items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><section className="hidden lg:block"><div className="mb-10 flex items-center gap-3 text-sm font-semibold tracking-[0.16em] text-moss uppercase"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-moss text-paper"><ShieldCheck size={21} /></span> EduConnect</div><p className="mb-5 max-w-lg text-5xl font-semibold leading-[1.03]">Le lien officiel entre votre famille et l&apos;école.</p><p className="max-w-md text-lg leading-8 text-ink/60">Retrouvez les informations importantes au même endroit.</p><div className="mt-14 flex items-center gap-3 text-sm text-ink/55"><LockKeyhole size={17} className="text-moss" /> Vos échanges restent sécurisés.</div></section><section className="mx-auto w-full max-w-md rounded-[2rem] border border-line bg-white p-7 shadow-soft sm:p-10"><div className="mb-8"><p className="mb-2 text-xs font-semibold tracking-[0.18em] text-moss uppercase">Espace EduConnect</p><h1 className="text-3xl font-semibold">Bienvenue</h1><p className="mt-3 leading-6 text-ink/60">Connectez-vous avec les identifiants de l&apos;établissement.</p></div><form onSubmit={handleSubmit} className="space-y-5"><div className="grid grid-cols-3 gap-2">{(['PARENT', 'STUDENT', 'STAFF'] as const).map((item) => <button type="button" key={item} onClick={() => { setRole(item); setIdentifier(''); setError(''); }} className={`category-tab justify-center ${role === item ? 'category-tab-active' : ''}`}>{item === 'PARENT' ? 'Parent' : item === 'STUDENT' ? 'Élève' : 'Personnel'}</button>)}</div><label className="block text-sm font-medium">{role === 'PARENT' ? 'Numéro de téléphone' : 'Matricule ou email'}<input required type={role === 'PARENT' ? 'tel' : 'text'} autoComplete="username" value={identifier} onChange={(event) => setIdentifier(event.target.value)} placeholder={role === 'PARENT' ? '07 00 00 00 00' : 'Matricule ou email'} className="field mt-2" /></label><label className="block text-sm font-medium">Mot de passe<input required type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} className="field mt-2" /></label>{error && <p className="notice-error">{error}</p>}<button disabled={busy} className="button-primary w-full">{busy ? 'Connexion...' : <>Se connecter <ArrowRight size={17} /><KeyRound size={17} /></>}</button></form><p className="mt-8 flex items-center justify-center gap-2 text-xs text-ink/45"><Phone size={14} /> Identifiants fournis par l&apos;école</p></section></div></main>;
}
