import { useState, useEffect, useCallback } from 'react';
import { Pencil, Plus, Mail, Lock, User as UserIcon, Phone } from 'lucide-react';
import { userService } from '@/services/user.service';
import UserLifecycleActions from '@/components/users/UserLifecycleActions';
import Table, { type Column } from '@/components/ui/Table';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Modal from '@/components/ui/Modal';
import Input from '@/components/ui/Input';
import Select from '@/components/ui/Select';
import SearchBar from '@/components/ui/SearchBar';
import { formatPhone, getRoleBadge } from '@/utils/formatters';
import type { User, UserRole } from '@/types';
import toast from 'react-hot-toast';
const emptyForm={firstName:'',lastName:'',email:'',phone:'',role:'STAFF' as UserRole,roleTitle:'',department:'',password:''};type FormData=typeof emptyForm;const roleOptions=[{value:'STAFF',label:'Personnel'}];
export default function StaffPage(){const [staff,setStaff]=useState<User[]>([]);const [pagination,setPagination]=useState({page:1,totalPages:1,total:0});const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState<string|null>(null);const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState<'all'|'active'|'inactive'>('all');const [modalOpen,setModalOpen]=useState(false);const [editingUser,setEditingUser]=useState<User|null>(null);const [form,setForm]=useState<FormData>(emptyForm);const [formErrors,setFormErrors]=useState<Partial<Record<keyof FormData,string>>>({});const [saving,setSaving]=useState(false);
 const fetchStaff=useCallback(async()=>{setLoading(true);setLoadError(null);try{const params:Record<string,string|number|boolean>={page:pagination.page,limit:20,role:'STAFF'};if(search)params.search=search;if(statusFilter!=='all')params.isActive=statusFilter==='active';const res=await userService.getUsers(params as any);setStaff(res.data.filter(u=>u.role==='STAFF'));setPagination({page:res.pagination.page,totalPages:res.pagination.totalPages,total:res.pagination.total})}catch(error){const message=error instanceof Error?error.message:'Impossible de charger le personnel';setLoadError(message);toast.error(message)}finally{setLoading(false)}},[pagination.page,search,statusFilter]);useEffect(()=>{fetchStaff()},[fetchStaff]);
 const openCreate=()=>{setEditingUser(null);setForm({...emptyForm});setFormErrors({});setModalOpen(true)};const openEdit=(u:User)=>{setEditingUser(u);setForm({firstName:u.firstName,lastName:u.lastName,email:u.email,phone:u.phone||'',role:'STAFF',roleTitle:u.roleTitle||'',department:u.department||'',password:''});setFormErrors({});setModalOpen(true)};const validate=()=>{const errors:typeof formErrors={};if(!form.firstName.trim())errors.firstName='Requis';if(!form.lastName.trim())errors.lastName='Requis';if(!form.email.trim())errors.email='Requis';if(!form.roleTitle.trim())errors.roleTitle='Requis';if(!editingUser&&!form.password)errors.password='Requis';setFormErrors(errors);return Object.keys(errors).length===0};const handleSave=async()=>{if(!validate())return;setSaving(true);try{const payload={...form,role:'STAFF' as const,role_title:form.roleTitle,department:form.department};if(editingUser){const {password:_,role:__,...data}=payload;await userService.updateUser(editingUser.id,data as any)}else await userService.createUser(payload as any);toast.success(editingUser?'Personnel modifié':'Personnel ajouté');setModalOpen(false);await fetchStaff()}catch(error){toast.error(error instanceof Error?error.message:'Opération impossible')}finally{setSaving(false)}};
 const columns:Column<User>[]=[{key:'name',header:'Nom complet',render:u=><span className="font-medium text-slate-900">{u.firstName} {u.lastName}</span>},{key:'matricule',header:'Matricule',render:u=><span className="text-sm text-slate-600">{u.matricule||'—'}</span>},{key:'role',header:'Rôle',render:()=>{const b=getRoleBadge('STAFF');return <span className={b.className}>{b.label}</span>}},{key:'fonction',header:'Fonction',render:u=><span className="text-sm text-slate-600">{u.roleTitle||'—'}</span>},{key:'departement',header:'Département',render:u=><span className="text-sm text-slate-600">{u.department||'—'}</span>},{key:'phone',header:'Téléphone',render:u=><span className="text-sm text-slate-600">{formatPhone(u.phone)}</span>},{key:'isActive',header:'Statut',render:u=>u.isActive?<span className="inline-flex rounded-md bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700">Actif</span>:<span className="inline-flex rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700">Inactif</span>},{key:'actions',header:'Actions',className:'text-right',render:u=><div className="flex items-center justify-end gap-1"><button aria-label={`Modifier ${u.firstName} ${u.lastName}`} onClick={()=>openEdit(u)} className="rounded-md p-1.5 text-slate-400 hover:bg-primary-50 hover:text-primary"><Pencil className="h-4 w-4"/></button><UserLifecycleActions user={u} onChanged={fetchStaff} label={`le membre du personnel ${u.firstName} ${u.lastName}`}/></div>}];
 return <div className="space-y-5"><div className="flex flex-col gap-3 border-b border-line pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-semibold tracking-tight text-slate-900">Personnel</h1><p className="mt-1 text-sm text-muted">Gérez les membres du personnel, leurs fonctions et leurs départements.</p></div><Button onClick={openCreate}><Plus className="h-4 w-4"/>Ajouter du personnel</Button></div><div className="flex flex-col gap-2 sm:flex-row sm:items-center"><div className="w-full sm:max-w-sm"><SearchBar onSearch={v=>{setSearch(v);setPagination(p=>({...p,page:1}))}} placeholder="Rechercher du personnel..."/></div><div className="flex gap-1 rounded-md border border-line bg-white p-1"><button className={`rounded px-3 py-1.5 text-xs font-medium ${statusFilter==='all'?'bg-slate-100 text-slate-900':'text-slate-500'}`} onClick={()=>{setStatusFilter('all');setPagination(p=>({...p,page:1}))}}>Tous</button><button className={`rounded px-3 py-1.5 text-xs font-medium ${statusFilter==='active'?'bg-emerald-50 text-emerald-700':'text-slate-500'}`} onClick={()=>{setStatusFilter('active');setPagination(p=>({...p,page:1}))}}>Actifs</button><button className={`rounded px-3 py-1.5 text-xs font-medium ${statusFilter==='inactive'?'bg-red-50 text-red-700':'text-slate-500'}`} onClick={()=>{setStatusFilter('inactive');setPagination(p=>({...p,page:1}))}}>Inactifs</button></div></div>{loadError&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{loadError}</div>}<Card className="!p-0 overflow-hidden"><Table columns={columns} data={staff} loading={loading} keyExtractor={u=>u.id} emptyMessage="Aucun personnel trouvé"/></Card>
 <Modal open={modalOpen} onClose={()=>setModalOpen(false)} title={editingUser?'Modifier le personnel':'Ajouter du personnel'} size="lg"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Input label="Prénom" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} error={formErrors.firstName} icon={<UserIcon className="h-4 w-4"/>}/><Input label="Nom" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} error={formErrors.lastName}/><Input label="E-mail" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} error={formErrors.email} icon={<Mail className="h-4 w-4"/>}/><Input label="Téléphone" type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} icon={<Phone className="h-4 w-4"/>}/><Select label="Rôle" options={roleOptions} value="STAFF" onChange={()=>undefined}/><Input label="Fonction" value={form.roleTitle} onChange={e=>setForm({...form,roleTitle:e.target.value})} placeholder="Ex: Professeur de maths" error={formErrors.roleTitle}/><Input label="Département" value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="Ex: Sciences"/>{!editingUser&&<Input label="Mot de passe" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} error={formErrors.password} icon={<Lock className="h-4 w-4"/>}/>}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={()=>setModalOpen(false)}>Annuler</Button><Button onClick={handleSave} loading={saving}>{editingUser?'Enregistrer':'Créer'}</Button></div></Modal></div>}
